{
 "title": "Linux服务器详情",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "server",
    "query": "label_values(node_uname_info,instance)"
   },
   {
    "name": "device",
    "label": "网卡",
    "query": "label_values(node_network_info{device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{instance=~\"$server\"})"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$server\",mode=\"idle\"}[1m])) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$server\"} / (node_memory_MemTotal_bytes{instance=~\"$server\"})))* 100"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max((node_filesystem_size_bytes{instance=~\"$server\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{instance=~\"$server\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {instance=~\"$server\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{instance=~\"$server\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{instance=~\"$server\",fstype=~\"ext.?|xfs\"})))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$server\",mode=\"system\"})"
    }
   ]
  },
  {
   "title": "内存",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$server\"} - 0"
    }
   ]
  },
  {
   "title": "每秒网络详情",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$server',device=~\"$device\"}[5m])*8",
     "legendFormat": "{{device}}下载"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$server',device=~\"$device\"}[5m])*8",
     "legendFormat": "{{device}}上传"
    }
   ]
  },
  {
   "title": "内存详情",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$server\"}",
     "legendFormat": "总内存"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$server\"} - node_memory_MemAvailable_bytes{instance=~\"$server\"}",
     "legendFormat": "已用内存"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$server\"}",
     "legendFormat": "可用内存"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$server\"}",
     "legendFormat": "buffers内存"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$server\"}",
     "legendFormat": "free内存"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$server\"}",
     "legendFormat": "cache内存"
    }
   ]
  },
  {
   "title": "各分区空间信息",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$server\",fstype=~\"ext.*|xfs\",mountpoint!~\".*pod.*\"}"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance=~\"$server\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}"
    }
   ]
  },
  {
   "title": "系统平均负载",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(count(node_cpu_seconds_total{instance=~\"$server\", mode='system'}) by (cpu,instance)) by(instance)",
     "legendFormat": "CPU总核数"
    },
    {
     "expr": "node_load5{instance=~\"$server\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "node_load15{instance=~\"$server\"}",
     "legendFormat": "15分钟负载"
    }
   ]
  }
 ]
}