{
 "title": "服务检测",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": "label_values(probe_success{job=\"status_check\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "STATUS",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$service\"}",
     "legendFormat": "{{_service_name}}"
    }
   ]
  },
  {
   "title": "TCP检测耗时",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~'$service'}",
     "legendFormat": "{{_service_name}}:{{instance}}"
    }
   ]
  },
  {
   "title": "服务连通性统计",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": " count_values('value',probe_success{instance=~\"$service\"})",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "TCP检测",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$service\"}"
    }
   ]
  }
 ]
}